/**
 * Generates `app/tokens.css` (Tailwind v4 @theme tokens) from
 * `constants/theme.ts` — the single source of truth for design tokens.
 *
 * Run manually with `npm run tokens`; also runs automatically before
 * `npm run dev` and `npm run build`.
 *
 * Namespaces emitted:
 *   colors            → --color-*            (bg-*, text-*, border-*, …)
 *   fontFamily        → --font-*             (font-sans, …)
 *   fontSize          → --text-*             (text-sm, text-4xl, …)
 *   fontWeight        → --font-weight-*      (font-bold, …)
 *   lineHeight        → --leading-*          (leading-tight, …)
 *   letterSpacing     → --tracking-*         (tracking-wide, …)
 *   borderRadius      → --radius-*           (rounded-lg, …)
 *   spacing           → --spacing-*          (p-4, gap-6, …)
 *   containerWidth    → --container-width-*  (w-[var(--container-width-lg)])
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const themeFile = join(root, "constants", "theme.ts");
const outFile = join(root, "app", "tokens.css");

const source = readFileSync(themeFile, "utf8");

const start = source.indexOf("export const theme = ");
if (start === -1) {
  throw new Error("Could not find `export const theme` in constants/theme.ts");
}

let body = source.slice(start + "export const theme = ".length);
const end = body.indexOf(";");
body = body.slice(0, end).replace(/ as const$/m, "");

// Evaluate the token object in a sandbox (the file is ours & controlled).
const theme = new Function(`return (${body});`)();

function kebabCase(key) {
  return key.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
}

function flatten(obj, prefix, lines) {
  for (const [key, value] of Object.entries(obj)) {
    const name = prefix ? `${prefix}-${kebabCase(key)}` : kebabCase(key);
    if (value !== null && typeof value === "object") {
      flatten(value, name, lines);
    } else {
      lines.push(`  --${name}: ${value};`);
    }
  }
}

const sections = {
  colors: "color",
  fontFamily: "font",
  fontSize: "text",
  fontWeight: "font-weight",
  lineHeight: "leading",
  letterSpacing: "tracking",
  borderRadius: "radius",
  spacing: "spacing",
  containerWidth: "container-width",
};

const blocks = Object.entries(sections).map(([key, prefix]) => {
  const lines = [];
  flatten(theme[key] ?? {}, prefix, lines);
  return lines.length ? `@theme {\n${lines.join("\n")}\n}` : null;
});

const css = `/* AUTO-GENERATED by scripts/generate-tokens.mjs — DO NOT EDIT. */
/* Source of truth: constants/theme.ts */

${blocks.filter(Boolean).join("\n\n")}
`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, `${css}\n`);
console.log(`✓ Generated app/tokens.css from constants/theme.ts`);
